### ISSUE TITLE
TypeError: object of type 'XX' has no len()

### ISSUE THREAD

**Issue by arnuschky** [hynek/structlog#123]
Following from the following statement in the docs, I expect that I can log any object and structlog converts it to a string (a feature much appreciated):

> All keywords are formatted using structlog.dev.ConsoleRenderer. That in turn uses repr() to serialize all values to strings. Thus, it’s easy to add support for logging of your own objects[*].

However, when I try to do this (eg, `log.debug(7)`, I get the following error:

```
Traceback (most recent call last):
  File "structlog_test.py", line 513, in <module>
    log.debug(x)
  File "/local/lib/python2.7/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/local/lib/python2.7/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/local/lib/python2.7/site-packages/structlog/dev.py", line 181, in __call__
    event = _pad(event, self._pad_event) + self._styles.reset + " "
  File "/local/lib/python2.7/site-packages/structlog/dev.py", line 36, in _pad
    missing = l - len(s)
TypeError: object of type 'int' has no len()
```

**Comment by hynek** [comment]
The `event` (i.e. first argument must be a string), the values in the key-value pairs should work.

I.e.

```python
log.debug("foo", some_key=7)
```

**Comment by arnuschky** [comment]
Yes, that works fine. I misinterpreted the above quote insofar that I thought it would allow me to write `log.msg(7)` or `log.debug(object)` but that's not the case. A pity, that would be really convenient.
