### ISSUE TITLE
error on sys.excepthook

### ISSUE THREAD

**Issue by rachmadaniHaryono** [hynek/structlog#127]
is there an option to automatically convert object to string?

i use structlog on my qt program and it catch my keyboard interrupt error, but can't print it due to error below

Version: 17.2.0

python3.5 on linux ubuntu17.04

```
Traceback (most recent call last):
  File "/home/q/.virtualenvs/happypanda/local/lib/python3.5/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/home/q/.virtualenvs/happypanda/local/lib/python3.5/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/home/q/.virtualenvs/happypanda/local/lib/python3.5/site-packages/structlog/dev.py", line 211, in __call__
    sio.write("\n" + exc)
TypeError: Can't convert 'KeyboardInterrupt' object to str implicitly
```

is there any other info you need it?

**Comment by hynek** [comment]
(How) did you configure structlog?  The default config has  `format_exc_info` in the processor list which *should* prevent this error from happening?!

**Comment by rachmadaniHaryono** [comment]
unfortunately i can't reproduce it so i will close the issue for now. code below is the main configuration for the logging.

```python
def main():
    log_handlers = []
    log_handlers.append(logging.handlers.RotatingFileHandler(
        'log_issue.log', maxBytes=1000000 * 10, encoding='utf-8', backupCount=2))
    logging.getLogger('').handlers = []
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)-8s %(levelname)-6s %(name)-6s %(message)s',
        datefmt='%d-%m %H:%M',
        handlers=log_handlers)
    log = structlog.getLogger(__name__)
    log.debug('test log', time=datetime.now())
    sys.excepthook = excepthook
    
def excepthook(ex_type, ex, tb):
    traceback.print_exception(ex_type, ex, tb)
```

is there a way to dump structlog configuration to json, so maybe i can provide better info next time?

**Comment by hynek** [comment]
Hm there's not.  It might be a good idea to add a `structlog.dump_config()`.
