### ISSUE TITLE
Output does not match show_off.py

### ISSUE THREAD

**Issue by AndrewGuenther** [hynek/structlog#387]
I'm trying to capture exception output similar to `show_off.py` has in the README. I have `better_exceptions` installed and I can see structlog is outputting exceptions using the standard `better_exceptions` format, but I'm curious how the custom formatting shown in the README was achieved...

For reference, my output for show_off.py looks like this:

```
2021-12-20 17:14.52 [debug    ] debugging is hard              a_list=[1, 2, 3]
2021-12-20 17:14.52 [info     ] informative!                   some_key=some_value
2021-12-20 17:14.52 [warning  ] uh-uh!
2021-12-20 17:14.52 [error    ] omg                            a_dict={'a': 42, 'b': 'foo'}
2021-12-20 17:14.52 [critical ] wtf                            what=SomeClass(x=1, y='z')
printing exception
<function better_traceback at 0x7f28803435e0>
2021-12-20 17:14.52 [error    ] poor me                        
Traceback (most recent call last):
  File "./basic_log.py", line 27, in make_call_stack_more_impressive
    print(SomeClass(d["y"], "foo"))
          │         └ {'x': 42}
          └ <class '__main__.SomeClass'>
KeyError: 'y'

2021-12-20 17:14.52 [info     ] all better now!                
Stack (most recent call last):
  File "./basic_log.py", line 33, in <module>
    make_call_stack_more_impressive()
  File "./basic_log.py", line 30, in make_call_stack_more_impressive
    log.info("all better now!", stack_info=True)
```

**Comment by hynek** [comment]
show_off.py is using rich that takes precedence over BE. It's documented somewhere but easy to miss.

**Comment by AndrewGuenther** [comment]
Ah, thanks!
