### ISSUE TITLE
percentage signs can't be logged in structlog==22.2.0

### ISSUE THREAD

**Issue by danielx** [hynek/structlog#479]
Hello, it seems the new 22.2.0 release breaks structlog if events/messages contains the `%` character.

```
$ pip freeze | grep structlog
structlog==22.2.0
```

---- 

```python
# main.py
import structlog

log = structlog.get_logger()

log.info("example.com/?q=Hello%2C%20World%21")
```

```
$ python main.py
Traceback (most recent call last):
  File "/home/daniel/work/structerr/main.py", line 5, in <module>
    log.info("example.com/?q=Hello%2C%20World%21")
  File "/home/daniel/.local/share/virtualenvs/structerr-1KsXSVL2/lib/python3.10/site-packages/structlog/_log_levels.py", line 156, in meth
    return self._proxy_to_logger(name, event % args, **kw)
TypeError: not enough arguments for format string
```

-----

``` python
# main.py
import structlog

log = structlog.get_logger()

log.info("50%")
```

```
$ python main.py
Traceback (most recent call last):
  File "/home/daniel/work/structerr/main.py", line 6, in <module>
    log.info("50%")
  File "/home/daniel/.local/share/virtualenvs/structerr-1KsXSVL2/lib/python3.10/site-packages/structlog/_log_levels.py", line 156, in meth
    return self._proxy_to_logger(name, event % args, **kw)
ValueError: incomplete format
```

**Comment by danielx** [comment]
It looks like this issue will also be fixed by #475

**Comment by hynek** [comment]
Great, thanks for finding it and sorry!

**Comment by hynek** [comment]
JFTR I've added https://github.com/hynek/structlog/commit/fc60f2fbb0523f1dc3d8eefeeb11fb19f441f33f to ensure it keeps working.

**Comment by hynek** [comment]
22.3 is on PyPI
