### ISSUE TITLE
KeyError: "Attempt to overwrite 'filename' in LogRecord"

### ISSUE THREAD

**Issue by luqasz** [hynek/structlog#486]
This is what I am using. Gunicorn + uvicorn app.
```python
elog = structlog.get_logger("gunicorn.error", )
alog = structlog.get_logger("gunicorn.error", )


class GunicornLogger:

    def __init__(self, cfg):
        self.cfg = cfg
        self.error_log = elog.bind()
        self.access_log = alog.bind()
        logging.getLogger().setLevel(logging.DEBUG) # bit hacky but only required to emit logs

    def debug(self, msg, *args, **kwargs) -> None:
        self.error_log.debug(msg, *args, **kwargs)

```

```python
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 105, in setup
    self.log.debug('Current configuration:\n{0}'.format(
  File "/app/src/myapp/logs.py", line 80, in debug
    self.error_log.debug(msg, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/structlog/stdlib.py", line 180, in debug
    return self._proxy_to_logger("debug", event, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/structlog/stdlib.py", line 247, in _proxy_to_logger
    return super()._proxy_to_logger(method_name, event=event, **event_kw)
  File "/usr/local/lib/python3.10/site-packages/structlog/_base.py", line 206, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1465, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1622, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args,
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1596, in makeRecord
    raise KeyError("Attempt to overwrite %r in LogRecord" % key)
KeyError: "Attempt to overwrite 'filename' in LogRecord"
```

**Comment by hynek** [comment]
That's interesting – looks like it's illegal to set a callsite parameter twice:

```python
    def makeRecord(self, name, level, fn, lno, msg, args, exc_info,
                   func=None, extra=None, sinfo=None):
        """
        A factory method which can be overridden in subclasses to create
        specialized LogRecords.
        """
        rv = _logRecordFactory(name, level, fn, lno, msg, args, exc_info, func,
                             sinfo)
        if extra is not None:
            for key in extra:
                if (key in ["message", "asctime"]) or (key in rv.__dict__):
                    raise KeyError("Attempt to overwrite %r in LogRecord" % key)
                rv.__dict__[key] = extra[key]
        return rv

```

**Comment by mett** [comment]
I ran into this issue as well, and I was wondering if anyone has found a work around for it?

**Comment by hynek** [comment]
OK so, the problem as far as I can tell is that we support multiple approaches how to interact with the standard library as documented in <https://www.structlog.org/en/stable/standard-library.html#suggested-configurations>.

The current code is optimized for the case of standard library log records flowing _into_ _structlog_.

If CPA detects a log record in the event dict, it extracts the callsite metadata and puts it into the event dict:

https://github.com/hynek/structlog/blob/ecaa15ac6b166ebca9f2b4f5cfdb4c4ec138a602/src/structlog/processors.py#L910-L919

The problem is when it goes the other way. Because we put the whole event dict into `extra` both in `render_to_log_kwargs`:

https://github.com/hynek/structlog/blob/ecaa15ac6b166ebca9f2b4f5cfdb4c4ec138a602/src/structlog/stdlib.py#L965

as well as `render_to_log_args_and_kwargs`:

https://github.com/hynek/structlog/blob/ecaa15ac6b166ebca9f2b4f5cfdb4c4ec138a602/src/structlog/stdlib.py#L936-L937

These processors convert the event dict into logging method arguments.

And the problem is that stdlib logging then tries to apply these values unconditionally to the log record. And if the log record already _has_ some of those values, you get the exception you're seeing. The beautiful symmetry we get when extracting the same names from log records blasts our foot away.

---

I think this needs to be fixed in `render_to_log_kwargs` and `render_to_log_args_and_kwargs` by not putting these fields under these names into `extra`. The question then is if they should be renamed or removed? Are there any weird side-effects I'm not thinking of? As usual, this is a problem of a impedance mismatch and _structlog_ trying to support all approaches. :|

**Comment by hynek** [comment]
Oh and wait, it might be y'all are holding it wrong!

The original bug report didn't mention it, but could it be y'all are using `ProcessorFormatter` on the stdlib side?

Because if so (and that's how I ran into this problem myself the other day), you must not use `render_to_*` but `wrap_for_formatter()` as documented in https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging

If not, I'd appreciate a complete reproducer (i.e. code I can run and see the problem).
