### ISSUE TITLE
Unexpected handling of exc_info in structlog v24 when using .exception

### ISSUE THREAD

**Issue by jf2** [hynek/structlog#590]
Hi.

The new handling of the exception level has introduced a somewhat surprising behaviour.

To reproduce
```
import sys
import structlog


def custom_exception_processor(logger, name, event_dict):
    if "exc_info" in event_dict:
        exc_type, exc_value, exc_tb = sys.exc_info()
        if exc_value is not None:
            event_dict["event"] = str(exc_value)
        del event_dict["exc_info"]
    return event_dict


structlog.configure(processors=[custom_exception_processor,
                                structlog.stdlib.add_log_level,
                                structlog.stdlib.add_logger_name,
                                structlog.dev.ConsoleRenderer(),
                                structlog.stdlib.ProcessorFormatter.wrap_for_formatter],
                    wrapper_class=structlog.stdlib.BoundLogger,
                    logger_factory=structlog.stdlib.LoggerFactory())
logger = structlog.getLogger("test_logger")
try:
    raise ValueError("test")
except ValueError:
    logger.exception("test", exc_info=True)
```

I would expect the output to simply read:
```
[error    ] test                           [test_logger]
```

Instead, it reads:
```
[error    ] test                           [test_logger]
Traceback (most recent call last):
  File "inconsistent_exc_info.py", line 23, in <module>
    raise ValueError("test")
ValueError: test
```

The problem is that the wrapped python logger has a default value of exc_info=True for .exception, which does not get overridden.
Not entirely sure whose responsibility it is (processor or bound logger) to handle this case.

It happens here:

```
structlog/_base.py:116 (BoundLoggerBase._process_event)

...
        for proc in self._processors:
            event_dict = proc(self._logger, method_name, event_dict)

        if isinstance(event_dict, (str, bytes, bytearray)):
            return (event_dict,), {}

```
The returned empty dictionary allows the exc_info to be set to True within the Python logger.

Note that in my reproduction example above, it also does not help if I force the `event_dict['exc_info'] = False`

Happy to hear your thoughts.

**Comment by hynek** [comment]
Hm, yeah this is a weird interplay that's as you write is not quite clear how it should be resolved.

A short-term fix for you is using `error()` instead of `exception()`, I guess.

Looks like we've got a similar problem solve on ProcessorFormatter in the form of keep_exc_info.

My best guess is that it should be an option on stdlib.BoundLogger to treat exc_info differently?

**Comment by hynek** [comment]
OK for posterity I took another look and this problem is two-fold but only affects ConsoleRenderer:

- we forward our event_dict to standard library logging at kwargs. `Logger.exception` has `exc_info=True` as kwarg.
- that means that we'd have to force an exc_info=False into it, however, exc_info gets popped out of the event_dict by ConsoleRenderer. It figures out that it should do nothing, but hides the fact from `Logger.exception`.

I think the best way forward would be to make exception handling optional in ConsoleRenderer? And if it's deactivated, exc_info is passed unchanged.

**Comment by Dhruv26** [comment]
Hi!

I've recently started using structlog and followed the configuration from the [standard library integration guide](https://www.structlog.org/en/stable/standard-library.html#rendering-within-structlog). I’ve run into the same issue described here and wanted to point out that it possibly also affects `JSONRenderer`, not just `ConsoleRenderer`.

It’s possible I’m misconfiguring something — but from my testing, this seems like a general interaction between `logger.exception()` and how `exc_info` is handled.

Here's a minimal snippet to reproduce the behavior using JSONRenderer:

<details><summary><h4>Code Snippet</h4></summary>

```python
import logging
import sys

import structlog

logger = structlog.get_logger(__name__)


def init_logging() -> None:
    logging.basicConfig(
        format="%(message)s",
        stream=sys.stdout,
        level=logging.INFO,
    )

    processors = [
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer(),
    ]
    structlog.configure(
        processors=processors,
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
    )


if __name__ == "__main__":
    init_logging()

    logger.info("Logging initialized successfully.")
    try:
        raise ValueError("An example error for testing logging.")
    except Exception as e:
        logger.exception("An error occurred")

```

</details> 

***Output***
```
❯ python structlog_snippet.py
{"event": "Logging initialized successfully.", "logger": "__main__", "level": "info", "timestamp": "2025-07-03T19:48:07.363483Z"}
{"event": "An error occurred", "logger": "__main__", "level": "error", "timestamp": "2025-07-03T19:48:07.363665Z", "exception": "Traceback (most recent call last):\n  File \"/Users/dhruvsegat/repos/mapping-service/dev/structlog_snippet.py\", line 41, in <module>\n    raise ValueError(\"An example error for testing logging.\")\nValueError: An example error for testing logging."}
Traceback (most recent call last):
  File "/Users/dhruvsegat/repos/mapping-service/dev/structlog_snippet.py", line 41, in <module>
    raise ValueError("An example error for testing logging.")
ValueError: An example error for testing logging.
```

As you can see, the traceback is rendered twice: once via `format_exc_info`, and again by the stdlib logger due to the implicit `exc_info=True` in `.exception()`. If this is considered a bug or an unintended interaction, I’d be happy to help with a PR based on your guidance. Let me know what you think!
